/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmailVerifiedRouteImport } from './routes/email-verified'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientProfileIndexRouteImport } from './routes/client/profile/index'
import { Route as ClientCompaniesIndexRouteImport } from './routes/client/companies/index'
import { Route as ClientProfileEditRouteImport } from './routes/client/profile/edit'
import { Route as ClientCompanyCompanyNameRouteImport } from './routes/client/company/$companyName'
import { Route as ClientCompaniesCreateRouteImport } from './routes/client/companies/create'
import { Route as ClientCompanyCompanyNameSettingRouteImport } from './routes/client/company/$companyName/setting'
import { Route as ClientCompanyCompanyNameBillingRouteImport } from './routes/client/company/$companyName/billing'
import { Route as ClientCompanyCompanyNameGeoTagIndexRouteImport } from './routes/client/company/$companyName/geo-tag/index'
import { Route as ClientCompanyCompanyNameMemberPermissionRouteImport } from './routes/client/company/$companyName/member/permission'
import { Route as ClientCompanyCompanyNameGeoTagCreateRouteImport } from './routes/client/company/$companyName/geo-tag/create'
import { Route as ClientCompanyCompanyNameMemberUserIndexRouteImport } from './routes/client/company/$companyName/member/user/index'
import { Route as ClientCompanyCompanyNameMemberRoleIndexRouteImport } from './routes/client/company/$companyName/member/role/index'
import { Route as ClientCompanyCompanyNameMemberUserCreateRouteImport } from './routes/client/company/$companyName/member/user/create'
import { Route as ClientCompanyCompanyNameMemberRoleCreateRouteImport } from './routes/client/company/$companyName/member/role/create'
import { Route as ClientCompanyCompanyNameMemberUserUserIdIndexRouteImport } from './routes/client/company/$companyName/member/user/$userId/index'
import { Route as ClientCompanyCompanyNameMemberRoleRoleIdIndexRouteImport } from './routes/client/company/$companyName/member/role/$roleId/index'
import { Route as ClientCompanyCompanyNameMemberUserUserIdEditRouteImport } from './routes/client/company/$companyName/member/user/$userId/edit'
import { Route as ClientCompanyCompanyNameMemberRoleRoleIdEditRouteImport } from './routes/client/company/$companyName/member/role/$roleId/edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileIndexRoute = ClientProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCompaniesIndexRoute = ClientCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileEditRoute = ClientProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCompanyCompanyNameRoute =
  ClientCompanyCompanyNameRouteImport.update({
    id: '/company/$companyName',
    path: '/company/$companyName',
    getParentRoute: () => ClientRoute,
  } as any)
const ClientCompaniesCreateRoute = ClientCompaniesCreateRouteImport.update({
  id: '/companies/create',
  path: '/companies/create',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCompanyCompanyNameSettingRoute =
  ClientCompanyCompanyNameSettingRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBillingRoute =
  ClientCompanyCompanyNameBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameGeoTagIndexRoute =
  ClientCompanyCompanyNameGeoTagIndexRouteImport.update({
    id: '/geo-tag/',
    path: '/geo-tag/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameMemberPermissionRoute =
  ClientCompanyCompanyNameMemberPermissionRouteImport.update({
    id: '/member/permission',
    path: '/member/permission',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameGeoTagCreateRoute =
  ClientCompanyCompanyNameGeoTagCreateRouteImport.update({
    id: '/geo-tag/create',
    path: '/geo-tag/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameMemberUserIndexRoute =
  ClientCompanyCompanyNameMemberUserIndexRouteImport.update({
    id: '/member/user/',
    path: '/member/user/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameMemberRoleIndexRoute =
  ClientCompanyCompanyNameMemberRoleIndexRouteImport.update({
    id: '/member/role/',
    path: '/member/role/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameMemberUserCreateRoute =
  ClientCompanyCompanyNameMemberUserCreateRouteImport.update({
    id: '/member/user/create',
    path: '/member/user/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameMemberRoleCreateRoute =
  ClientCompanyCompanyNameMemberRoleCreateRouteImport.update({
    id: '/member/role/create',
    path: '/member/role/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameMemberUserUserIdIndexRoute =
  ClientCompanyCompanyNameMemberUserUserIdIndexRouteImport.update({
    id: '/member/user/$userId/',
    path: '/member/user/$userId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameMemberRoleRoleIdIndexRoute =
  ClientCompanyCompanyNameMemberRoleRoleIdIndexRouteImport.update({
    id: '/member/role/$roleId/',
    path: '/member/role/$roleId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameMemberUserUserIdEditRoute =
  ClientCompanyCompanyNameMemberUserUserIdEditRouteImport.update({
    id: '/member/user/$userId/edit',
    path: '/member/user/$userId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameMemberRoleRoleIdEditRoute =
  ClientCompanyCompanyNameMemberRoleRoleIdEditRouteImport.update({
    id: '/member/role/$roleId/edit',
    path: '/member/role/$roleId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/client/companies/create': typeof ClientCompaniesCreateRoute
  '/client/company/$companyName': typeof ClientCompanyCompanyNameRouteWithChildren
  '/client/profile/edit': typeof ClientProfileEditRoute
  '/client/companies': typeof ClientCompaniesIndexRoute
  '/client/profile': typeof ClientProfileIndexRoute
  '/client/company/$companyName/billing': typeof ClientCompanyCompanyNameBillingRoute
  '/client/company/$companyName/setting': typeof ClientCompanyCompanyNameSettingRoute
  '/client/company/$companyName/geo-tag/create': typeof ClientCompanyCompanyNameGeoTagCreateRoute
  '/client/company/$companyName/member/permission': typeof ClientCompanyCompanyNameMemberPermissionRoute
  '/client/company/$companyName/geo-tag': typeof ClientCompanyCompanyNameGeoTagIndexRoute
  '/client/company/$companyName/member/role/create': typeof ClientCompanyCompanyNameMemberRoleCreateRoute
  '/client/company/$companyName/member/user/create': typeof ClientCompanyCompanyNameMemberUserCreateRoute
  '/client/company/$companyName/member/role': typeof ClientCompanyCompanyNameMemberRoleIndexRoute
  '/client/company/$companyName/member/user': typeof ClientCompanyCompanyNameMemberUserIndexRoute
  '/client/company/$companyName/member/role/$roleId/edit': typeof ClientCompanyCompanyNameMemberRoleRoleIdEditRoute
  '/client/company/$companyName/member/user/$userId/edit': typeof ClientCompanyCompanyNameMemberUserUserIdEditRoute
  '/client/company/$companyName/member/role/$roleId': typeof ClientCompanyCompanyNameMemberRoleRoleIdIndexRoute
  '/client/company/$companyName/member/user/$userId': typeof ClientCompanyCompanyNameMemberUserUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/client/companies/create': typeof ClientCompaniesCreateRoute
  '/client/company/$companyName': typeof ClientCompanyCompanyNameRouteWithChildren
  '/client/profile/edit': typeof ClientProfileEditRoute
  '/client/companies': typeof ClientCompaniesIndexRoute
  '/client/profile': typeof ClientProfileIndexRoute
  '/client/company/$companyName/billing': typeof ClientCompanyCompanyNameBillingRoute
  '/client/company/$companyName/setting': typeof ClientCompanyCompanyNameSettingRoute
  '/client/company/$companyName/geo-tag/create': typeof ClientCompanyCompanyNameGeoTagCreateRoute
  '/client/company/$companyName/member/permission': typeof ClientCompanyCompanyNameMemberPermissionRoute
  '/client/company/$companyName/geo-tag': typeof ClientCompanyCompanyNameGeoTagIndexRoute
  '/client/company/$companyName/member/role/create': typeof ClientCompanyCompanyNameMemberRoleCreateRoute
  '/client/company/$companyName/member/user/create': typeof ClientCompanyCompanyNameMemberUserCreateRoute
  '/client/company/$companyName/member/role': typeof ClientCompanyCompanyNameMemberRoleIndexRoute
  '/client/company/$companyName/member/user': typeof ClientCompanyCompanyNameMemberUserIndexRoute
  '/client/company/$companyName/member/role/$roleId/edit': typeof ClientCompanyCompanyNameMemberRoleRoleIdEditRoute
  '/client/company/$companyName/member/user/$userId/edit': typeof ClientCompanyCompanyNameMemberUserUserIdEditRoute
  '/client/company/$companyName/member/role/$roleId': typeof ClientCompanyCompanyNameMemberRoleRoleIdIndexRoute
  '/client/company/$companyName/member/user/$userId': typeof ClientCompanyCompanyNameMemberUserUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/client/companies/create': typeof ClientCompaniesCreateRoute
  '/client/company/$companyName': typeof ClientCompanyCompanyNameRouteWithChildren
  '/client/profile/edit': typeof ClientProfileEditRoute
  '/client/companies/': typeof ClientCompaniesIndexRoute
  '/client/profile/': typeof ClientProfileIndexRoute
  '/client/company/$companyName/billing': typeof ClientCompanyCompanyNameBillingRoute
  '/client/company/$companyName/setting': typeof ClientCompanyCompanyNameSettingRoute
  '/client/company/$companyName/geo-tag/create': typeof ClientCompanyCompanyNameGeoTagCreateRoute
  '/client/company/$companyName/member/permission': typeof ClientCompanyCompanyNameMemberPermissionRoute
  '/client/company/$companyName/geo-tag/': typeof ClientCompanyCompanyNameGeoTagIndexRoute
  '/client/company/$companyName/member/role/create': typeof ClientCompanyCompanyNameMemberRoleCreateRoute
  '/client/company/$companyName/member/user/create': typeof ClientCompanyCompanyNameMemberUserCreateRoute
  '/client/company/$companyName/member/role/': typeof ClientCompanyCompanyNameMemberRoleIndexRoute
  '/client/company/$companyName/member/user/': typeof ClientCompanyCompanyNameMemberUserIndexRoute
  '/client/company/$companyName/member/role/$roleId/edit': typeof ClientCompanyCompanyNameMemberRoleRoleIdEditRoute
  '/client/company/$companyName/member/user/$userId/edit': typeof ClientCompanyCompanyNameMemberUserUserIdEditRoute
  '/client/company/$companyName/member/role/$roleId/': typeof ClientCompanyCompanyNameMemberRoleRoleIdIndexRoute
  '/client/company/$companyName/member/user/$userId/': typeof ClientCompanyCompanyNameMemberUserUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/email-verified'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/client/companies/create'
    | '/client/company/$companyName'
    | '/client/profile/edit'
    | '/client/companies'
    | '/client/profile'
    | '/client/company/$companyName/billing'
    | '/client/company/$companyName/setting'
    | '/client/company/$companyName/geo-tag/create'
    | '/client/company/$companyName/member/permission'
    | '/client/company/$companyName/geo-tag'
    | '/client/company/$companyName/member/role/create'
    | '/client/company/$companyName/member/user/create'
    | '/client/company/$companyName/member/role'
    | '/client/company/$companyName/member/user'
    | '/client/company/$companyName/member/role/$roleId/edit'
    | '/client/company/$companyName/member/user/$userId/edit'
    | '/client/company/$companyName/member/role/$roleId'
    | '/client/company/$companyName/member/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/email-verified'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/client/companies/create'
    | '/client/company/$companyName'
    | '/client/profile/edit'
    | '/client/companies'
    | '/client/profile'
    | '/client/company/$companyName/billing'
    | '/client/company/$companyName/setting'
    | '/client/company/$companyName/geo-tag/create'
    | '/client/company/$companyName/member/permission'
    | '/client/company/$companyName/geo-tag'
    | '/client/company/$companyName/member/role/create'
    | '/client/company/$companyName/member/user/create'
    | '/client/company/$companyName/member/role'
    | '/client/company/$companyName/member/user'
    | '/client/company/$companyName/member/role/$roleId/edit'
    | '/client/company/$companyName/member/user/$userId/edit'
    | '/client/company/$companyName/member/role/$roleId'
    | '/client/company/$companyName/member/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/email-verified'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/client/companies/create'
    | '/client/company/$companyName'
    | '/client/profile/edit'
    | '/client/companies/'
    | '/client/profile/'
    | '/client/company/$companyName/billing'
    | '/client/company/$companyName/setting'
    | '/client/company/$companyName/geo-tag/create'
    | '/client/company/$companyName/member/permission'
    | '/client/company/$companyName/geo-tag/'
    | '/client/company/$companyName/member/role/create'
    | '/client/company/$companyName/member/user/create'
    | '/client/company/$companyName/member/role/'
    | '/client/company/$companyName/member/user/'
    | '/client/company/$companyName/member/role/$roleId/edit'
    | '/client/company/$companyName/member/user/$userId/edit'
    | '/client/company/$companyName/member/role/$roleId/'
    | '/client/company/$companyName/member/user/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profile/': {
      id: '/client/profile/'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/companies/': {
      id: '/client/companies/'
      path: '/companies'
      fullPath: '/client/companies'
      preLoaderRoute: typeof ClientCompaniesIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile/edit': {
      id: '/client/profile/edit'
      path: '/profile/edit'
      fullPath: '/client/profile/edit'
      preLoaderRoute: typeof ClientProfileEditRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/company/$companyName': {
      id: '/client/company/$companyName'
      path: '/company/$companyName'
      fullPath: '/client/company/$companyName'
      preLoaderRoute: typeof ClientCompanyCompanyNameRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/companies/create': {
      id: '/client/companies/create'
      path: '/companies/create'
      fullPath: '/client/companies/create'
      preLoaderRoute: typeof ClientCompaniesCreateRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/company/$companyName/setting': {
      id: '/client/company/$companyName/setting'
      path: '/setting'
      fullPath: '/client/company/$companyName/setting'
      preLoaderRoute: typeof ClientCompanyCompanyNameSettingRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/billing': {
      id: '/client/company/$companyName/billing'
      path: '/billing'
      fullPath: '/client/company/$companyName/billing'
      preLoaderRoute: typeof ClientCompanyCompanyNameBillingRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/geo-tag/': {
      id: '/client/company/$companyName/geo-tag/'
      path: '/geo-tag'
      fullPath: '/client/company/$companyName/geo-tag'
      preLoaderRoute: typeof ClientCompanyCompanyNameGeoTagIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/member/permission': {
      id: '/client/company/$companyName/member/permission'
      path: '/member/permission'
      fullPath: '/client/company/$companyName/member/permission'
      preLoaderRoute: typeof ClientCompanyCompanyNameMemberPermissionRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/geo-tag/create': {
      id: '/client/company/$companyName/geo-tag/create'
      path: '/geo-tag/create'
      fullPath: '/client/company/$companyName/geo-tag/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameGeoTagCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/member/user/': {
      id: '/client/company/$companyName/member/user/'
      path: '/member/user'
      fullPath: '/client/company/$companyName/member/user'
      preLoaderRoute: typeof ClientCompanyCompanyNameMemberUserIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/member/role/': {
      id: '/client/company/$companyName/member/role/'
      path: '/member/role'
      fullPath: '/client/company/$companyName/member/role'
      preLoaderRoute: typeof ClientCompanyCompanyNameMemberRoleIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/member/user/create': {
      id: '/client/company/$companyName/member/user/create'
      path: '/member/user/create'
      fullPath: '/client/company/$companyName/member/user/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameMemberUserCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/member/role/create': {
      id: '/client/company/$companyName/member/role/create'
      path: '/member/role/create'
      fullPath: '/client/company/$companyName/member/role/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameMemberRoleCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/member/user/$userId/': {
      id: '/client/company/$companyName/member/user/$userId/'
      path: '/member/user/$userId'
      fullPath: '/client/company/$companyName/member/user/$userId'
      preLoaderRoute: typeof ClientCompanyCompanyNameMemberUserUserIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/member/role/$roleId/': {
      id: '/client/company/$companyName/member/role/$roleId/'
      path: '/member/role/$roleId'
      fullPath: '/client/company/$companyName/member/role/$roleId'
      preLoaderRoute: typeof ClientCompanyCompanyNameMemberRoleRoleIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/member/user/$userId/edit': {
      id: '/client/company/$companyName/member/user/$userId/edit'
      path: '/member/user/$userId/edit'
      fullPath: '/client/company/$companyName/member/user/$userId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameMemberUserUserIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/member/role/$roleId/edit': {
      id: '/client/company/$companyName/member/role/$roleId/edit'
      path: '/member/role/$roleId/edit'
      fullPath: '/client/company/$companyName/member/role/$roleId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameMemberRoleRoleIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
  }
}

interface ClientCompanyCompanyNameRouteChildren {
  ClientCompanyCompanyNameBillingRoute: typeof ClientCompanyCompanyNameBillingRoute
  ClientCompanyCompanyNameSettingRoute: typeof ClientCompanyCompanyNameSettingRoute
  ClientCompanyCompanyNameGeoTagCreateRoute: typeof ClientCompanyCompanyNameGeoTagCreateRoute
  ClientCompanyCompanyNameMemberPermissionRoute: typeof ClientCompanyCompanyNameMemberPermissionRoute
  ClientCompanyCompanyNameGeoTagIndexRoute: typeof ClientCompanyCompanyNameGeoTagIndexRoute
  ClientCompanyCompanyNameMemberRoleCreateRoute: typeof ClientCompanyCompanyNameMemberRoleCreateRoute
  ClientCompanyCompanyNameMemberUserCreateRoute: typeof ClientCompanyCompanyNameMemberUserCreateRoute
  ClientCompanyCompanyNameMemberRoleIndexRoute: typeof ClientCompanyCompanyNameMemberRoleIndexRoute
  ClientCompanyCompanyNameMemberUserIndexRoute: typeof ClientCompanyCompanyNameMemberUserIndexRoute
  ClientCompanyCompanyNameMemberRoleRoleIdEditRoute: typeof ClientCompanyCompanyNameMemberRoleRoleIdEditRoute
  ClientCompanyCompanyNameMemberUserUserIdEditRoute: typeof ClientCompanyCompanyNameMemberUserUserIdEditRoute
  ClientCompanyCompanyNameMemberRoleRoleIdIndexRoute: typeof ClientCompanyCompanyNameMemberRoleRoleIdIndexRoute
  ClientCompanyCompanyNameMemberUserUserIdIndexRoute: typeof ClientCompanyCompanyNameMemberUserUserIdIndexRoute
}

const ClientCompanyCompanyNameRouteChildren: ClientCompanyCompanyNameRouteChildren =
  {
    ClientCompanyCompanyNameBillingRoute: ClientCompanyCompanyNameBillingRoute,
    ClientCompanyCompanyNameSettingRoute: ClientCompanyCompanyNameSettingRoute,
    ClientCompanyCompanyNameGeoTagCreateRoute:
      ClientCompanyCompanyNameGeoTagCreateRoute,
    ClientCompanyCompanyNameMemberPermissionRoute:
      ClientCompanyCompanyNameMemberPermissionRoute,
    ClientCompanyCompanyNameGeoTagIndexRoute:
      ClientCompanyCompanyNameGeoTagIndexRoute,
    ClientCompanyCompanyNameMemberRoleCreateRoute:
      ClientCompanyCompanyNameMemberRoleCreateRoute,
    ClientCompanyCompanyNameMemberUserCreateRoute:
      ClientCompanyCompanyNameMemberUserCreateRoute,
    ClientCompanyCompanyNameMemberRoleIndexRoute:
      ClientCompanyCompanyNameMemberRoleIndexRoute,
    ClientCompanyCompanyNameMemberUserIndexRoute:
      ClientCompanyCompanyNameMemberUserIndexRoute,
    ClientCompanyCompanyNameMemberRoleRoleIdEditRoute:
      ClientCompanyCompanyNameMemberRoleRoleIdEditRoute,
    ClientCompanyCompanyNameMemberUserUserIdEditRoute:
      ClientCompanyCompanyNameMemberUserUserIdEditRoute,
    ClientCompanyCompanyNameMemberRoleRoleIdIndexRoute:
      ClientCompanyCompanyNameMemberRoleRoleIdIndexRoute,
    ClientCompanyCompanyNameMemberUserUserIdIndexRoute:
      ClientCompanyCompanyNameMemberUserUserIdIndexRoute,
  }

const ClientCompanyCompanyNameRouteWithChildren =
  ClientCompanyCompanyNameRoute._addFileChildren(
    ClientCompanyCompanyNameRouteChildren,
  )

interface ClientRouteChildren {
  ClientCompaniesCreateRoute: typeof ClientCompaniesCreateRoute
  ClientCompanyCompanyNameRoute: typeof ClientCompanyCompanyNameRouteWithChildren
  ClientProfileEditRoute: typeof ClientProfileEditRoute
  ClientCompaniesIndexRoute: typeof ClientCompaniesIndexRoute
  ClientProfileIndexRoute: typeof ClientProfileIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientCompaniesCreateRoute: ClientCompaniesCreateRoute,
  ClientCompanyCompanyNameRoute: ClientCompanyCompanyNameRouteWithChildren,
  ClientProfileEditRoute: ClientProfileEditRoute,
  ClientCompaniesIndexRoute: ClientCompaniesIndexRoute,
  ClientProfileIndexRoute: ClientProfileIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  EmailVerifiedRoute: EmailVerifiedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
