/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmailVerifiedRouteImport } from './routes/email-verified'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientProfileIndexRouteImport } from './routes/client/profile/index'
import { Route as ClientCompaniesIndexRouteImport } from './routes/client/companies/index'
import { Route as ClientProfileEditRouteImport } from './routes/client/profile/edit'
import { Route as ClientCompanyCompanyNameRouteImport } from './routes/client/company/$companyName'
import { Route as ClientCompaniesCreateRouteImport } from './routes/client/companies/create'
import { Route as ClientCompanyCompanyNameSettingRouteImport } from './routes/client/company/$companyName/setting'
import { Route as ClientCompanyCompanyNameBillingRouteImport } from './routes/client/company/$companyName/billing'
import { Route as ClientCompanyCompanyNameGeoTagIndexRouteImport } from './routes/client/company/$companyName/geo-tag/index'
import { Route as ClientCompanyCompanyNameCommodityIndexRouteImport } from './routes/client/company/$companyName/commodity/index'
import { Route as ClientCompanyCompanyNameBatchIndexRouteImport } from './routes/client/company/$companyName/batch/index'
import { Route as ClientCompanyCompanyNameGeoTagCreateRouteImport } from './routes/client/company/$companyName/geo-tag/create'
import { Route as ClientCompanyCompanyNameCommodityCreateRouteImport } from './routes/client/company/$companyName/commodity/create'
import { Route as ClientCompanyCompanyNameBatchCreateRouteImport } from './routes/client/company/$companyName/batch/create'
import { Route as ClientCompanyCompanyNameAdminPermissionRouteImport } from './routes/client/company/$companyName/admin/permission'
import { Route as ClientCompanyCompanyNameWorkerIndividualIndexRouteImport } from './routes/client/company/$companyName/worker/individual/index'
import { Route as ClientCompanyCompanyNameWorkerGroupIndexRouteImport } from './routes/client/company/$companyName/worker/group/index'
import { Route as ClientCompanyCompanyNameGeoTagLandIdIndexRouteImport } from './routes/client/company/$companyName/geo-tag/$landId/index'
import { Route as ClientCompanyCompanyNameCommodityCommodityIdIndexRouteImport } from './routes/client/company/$companyName/commodity/$commodityId/index'
import { Route as ClientCompanyCompanyNameBatchBatchIdIndexRouteImport } from './routes/client/company/$companyName/batch/$batchId/index'
import { Route as ClientCompanyCompanyNameAdminUserIndexRouteImport } from './routes/client/company/$companyName/admin/user/index'
import { Route as ClientCompanyCompanyNameAdminRoleIndexRouteImport } from './routes/client/company/$companyName/admin/role/index'
import { Route as ClientCompanyCompanyNameWorkerIndividualCreateRouteImport } from './routes/client/company/$companyName/worker/individual/create'
import { Route as ClientCompanyCompanyNameWorkerGroupCreateRouteImport } from './routes/client/company/$companyName/worker/group/create'
import { Route as ClientCompanyCompanyNameGeoTagLandIdEditRouteImport } from './routes/client/company/$companyName/geo-tag/$landId/edit'
import { Route as ClientCompanyCompanyNameCommodityCommodityIdEditRouteImport } from './routes/client/company/$companyName/commodity/$commodityId/edit'
import { Route as ClientCompanyCompanyNameBatchBatchIdEditRouteImport } from './routes/client/company/$companyName/batch/$batchId/edit'
import { Route as ClientCompanyCompanyNameAdminUserCreateRouteImport } from './routes/client/company/$companyName/admin/user/create'
import { Route as ClientCompanyCompanyNameAdminRoleCreateRouteImport } from './routes/client/company/$companyName/admin/role/create'
import { Route as ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRouteImport } from './routes/client/company/$companyName/worker/individual/$farmerId/index'
import { Route as ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRouteImport } from './routes/client/company/$companyName/worker/group/$farmerGroupId/index'
import { Route as ClientCompanyCompanyNameAdminUserUserIdIndexRouteImport } from './routes/client/company/$companyName/admin/user/$userId/index'
import { Route as ClientCompanyCompanyNameAdminRoleRoleIdIndexRouteImport } from './routes/client/company/$companyName/admin/role/$roleId/index'
import { Route as ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRouteImport } from './routes/client/company/$companyName/worker/individual/$farmerId/edit'
import { Route as ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRouteImport } from './routes/client/company/$companyName/worker/group/$farmerGroupId/edit'
import { Route as ClientCompanyCompanyNameBatchBatchIdSourceCreateRouteImport } from './routes/client/company/$companyName/batch/$batchId/source/create'
import { Route as ClientCompanyCompanyNameBatchBatchIdAttributeCreateRouteImport } from './routes/client/company/$companyName/batch/$batchId/attribute/create'
import { Route as ClientCompanyCompanyNameAdminUserUserIdEditRouteImport } from './routes/client/company/$companyName/admin/user/$userId/edit'
import { Route as ClientCompanyCompanyNameAdminRoleRoleIdEditRouteImport } from './routes/client/company/$companyName/admin/role/$roleId/edit'
import { Route as ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRouteImport } from './routes/client/company/$companyName/batch/$batchId/source/$sourceId/index'
import { Route as ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRouteImport } from './routes/client/company/$companyName/batch/$batchId/attribute/$attributeId/index'
import { Route as ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRouteImport } from './routes/client/company/$companyName/batch/$batchId/source/$sourceId/edit'
import { Route as ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRouteImport } from './routes/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileIndexRoute = ClientProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCompaniesIndexRoute = ClientCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileEditRoute = ClientProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCompanyCompanyNameRoute =
  ClientCompanyCompanyNameRouteImport.update({
    id: '/company/$companyName',
    path: '/company/$companyName',
    getParentRoute: () => ClientRoute,
  } as any)
const ClientCompaniesCreateRoute = ClientCompaniesCreateRouteImport.update({
  id: '/companies/create',
  path: '/companies/create',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCompanyCompanyNameSettingRoute =
  ClientCompanyCompanyNameSettingRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBillingRoute =
  ClientCompanyCompanyNameBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameGeoTagIndexRoute =
  ClientCompanyCompanyNameGeoTagIndexRouteImport.update({
    id: '/geo-tag/',
    path: '/geo-tag/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameCommodityIndexRoute =
  ClientCompanyCompanyNameCommodityIndexRouteImport.update({
    id: '/commodity/',
    path: '/commodity/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBatchIndexRoute =
  ClientCompanyCompanyNameBatchIndexRouteImport.update({
    id: '/batch/',
    path: '/batch/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameGeoTagCreateRoute =
  ClientCompanyCompanyNameGeoTagCreateRouteImport.update({
    id: '/geo-tag/create',
    path: '/geo-tag/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameCommodityCreateRoute =
  ClientCompanyCompanyNameCommodityCreateRouteImport.update({
    id: '/commodity/create',
    path: '/commodity/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBatchCreateRoute =
  ClientCompanyCompanyNameBatchCreateRouteImport.update({
    id: '/batch/create',
    path: '/batch/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameAdminPermissionRoute =
  ClientCompanyCompanyNameAdminPermissionRouteImport.update({
    id: '/admin/permission',
    path: '/admin/permission',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameWorkerIndividualIndexRoute =
  ClientCompanyCompanyNameWorkerIndividualIndexRouteImport.update({
    id: '/worker/individual/',
    path: '/worker/individual/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameWorkerGroupIndexRoute =
  ClientCompanyCompanyNameWorkerGroupIndexRouteImport.update({
    id: '/worker/group/',
    path: '/worker/group/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameGeoTagLandIdIndexRoute =
  ClientCompanyCompanyNameGeoTagLandIdIndexRouteImport.update({
    id: '/geo-tag/$landId/',
    path: '/geo-tag/$landId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameCommodityCommodityIdIndexRoute =
  ClientCompanyCompanyNameCommodityCommodityIdIndexRouteImport.update({
    id: '/commodity/$commodityId/',
    path: '/commodity/$commodityId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBatchBatchIdIndexRoute =
  ClientCompanyCompanyNameBatchBatchIdIndexRouteImport.update({
    id: '/batch/$batchId/',
    path: '/batch/$batchId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameAdminUserIndexRoute =
  ClientCompanyCompanyNameAdminUserIndexRouteImport.update({
    id: '/admin/user/',
    path: '/admin/user/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameAdminRoleIndexRoute =
  ClientCompanyCompanyNameAdminRoleIndexRouteImport.update({
    id: '/admin/role/',
    path: '/admin/role/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameWorkerIndividualCreateRoute =
  ClientCompanyCompanyNameWorkerIndividualCreateRouteImport.update({
    id: '/worker/individual/create',
    path: '/worker/individual/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameWorkerGroupCreateRoute =
  ClientCompanyCompanyNameWorkerGroupCreateRouteImport.update({
    id: '/worker/group/create',
    path: '/worker/group/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameGeoTagLandIdEditRoute =
  ClientCompanyCompanyNameGeoTagLandIdEditRouteImport.update({
    id: '/geo-tag/$landId/edit',
    path: '/geo-tag/$landId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameCommodityCommodityIdEditRoute =
  ClientCompanyCompanyNameCommodityCommodityIdEditRouteImport.update({
    id: '/commodity/$commodityId/edit',
    path: '/commodity/$commodityId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBatchBatchIdEditRoute =
  ClientCompanyCompanyNameBatchBatchIdEditRouteImport.update({
    id: '/batch/$batchId/edit',
    path: '/batch/$batchId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameAdminUserCreateRoute =
  ClientCompanyCompanyNameAdminUserCreateRouteImport.update({
    id: '/admin/user/create',
    path: '/admin/user/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameAdminRoleCreateRoute =
  ClientCompanyCompanyNameAdminRoleCreateRouteImport.update({
    id: '/admin/role/create',
    path: '/admin/role/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRoute =
  ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRouteImport.update({
    id: '/worker/individual/$farmerId/',
    path: '/worker/individual/$farmerId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRoute =
  ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRouteImport.update({
    id: '/worker/group/$farmerGroupId/',
    path: '/worker/group/$farmerGroupId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameAdminUserUserIdIndexRoute =
  ClientCompanyCompanyNameAdminUserUserIdIndexRouteImport.update({
    id: '/admin/user/$userId/',
    path: '/admin/user/$userId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameAdminRoleRoleIdIndexRoute =
  ClientCompanyCompanyNameAdminRoleRoleIdIndexRouteImport.update({
    id: '/admin/role/$roleId/',
    path: '/admin/role/$roleId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRoute =
  ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRouteImport.update({
    id: '/worker/individual/$farmerId/edit',
    path: '/worker/individual/$farmerId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRoute =
  ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRouteImport.update({
    id: '/worker/group/$farmerGroupId/edit',
    path: '/worker/group/$farmerGroupId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBatchBatchIdSourceCreateRoute =
  ClientCompanyCompanyNameBatchBatchIdSourceCreateRouteImport.update({
    id: '/batch/$batchId/source/create',
    path: '/batch/$batchId/source/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBatchBatchIdAttributeCreateRoute =
  ClientCompanyCompanyNameBatchBatchIdAttributeCreateRouteImport.update({
    id: '/batch/$batchId/attribute/create',
    path: '/batch/$batchId/attribute/create',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameAdminUserUserIdEditRoute =
  ClientCompanyCompanyNameAdminUserUserIdEditRouteImport.update({
    id: '/admin/user/$userId/edit',
    path: '/admin/user/$userId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameAdminRoleRoleIdEditRoute =
  ClientCompanyCompanyNameAdminRoleRoleIdEditRouteImport.update({
    id: '/admin/role/$roleId/edit',
    path: '/admin/role/$roleId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRoute =
  ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRouteImport.update({
    id: '/batch/$batchId/source/$sourceId/',
    path: '/batch/$batchId/source/$sourceId/',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRoute =
  ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRouteImport.update(
    {
      id: '/batch/$batchId/attribute/$attributeId/',
      path: '/batch/$batchId/attribute/$attributeId/',
      getParentRoute: () => ClientCompanyCompanyNameRoute,
    } as any,
  )
const ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRoute =
  ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRouteImport.update({
    id: '/batch/$batchId/source/$sourceId/edit',
    path: '/batch/$batchId/source/$sourceId/edit',
    getParentRoute: () => ClientCompanyCompanyNameRoute,
  } as any)
const ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRoute =
  ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRouteImport.update(
    {
      id: '/batch/$batchId/attribute/$attributeId/edit',
      path: '/batch/$batchId/attribute/$attributeId/edit',
      getParentRoute: () => ClientCompanyCompanyNameRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/client/companies/create': typeof ClientCompaniesCreateRoute
  '/client/company/$companyName': typeof ClientCompanyCompanyNameRouteWithChildren
  '/client/profile/edit': typeof ClientProfileEditRoute
  '/client/companies': typeof ClientCompaniesIndexRoute
  '/client/profile': typeof ClientProfileIndexRoute
  '/client/company/$companyName/billing': typeof ClientCompanyCompanyNameBillingRoute
  '/client/company/$companyName/setting': typeof ClientCompanyCompanyNameSettingRoute
  '/client/company/$companyName/admin/permission': typeof ClientCompanyCompanyNameAdminPermissionRoute
  '/client/company/$companyName/batch/create': typeof ClientCompanyCompanyNameBatchCreateRoute
  '/client/company/$companyName/commodity/create': typeof ClientCompanyCompanyNameCommodityCreateRoute
  '/client/company/$companyName/geo-tag/create': typeof ClientCompanyCompanyNameGeoTagCreateRoute
  '/client/company/$companyName/batch': typeof ClientCompanyCompanyNameBatchIndexRoute
  '/client/company/$companyName/commodity': typeof ClientCompanyCompanyNameCommodityIndexRoute
  '/client/company/$companyName/geo-tag': typeof ClientCompanyCompanyNameGeoTagIndexRoute
  '/client/company/$companyName/admin/role/create': typeof ClientCompanyCompanyNameAdminRoleCreateRoute
  '/client/company/$companyName/admin/user/create': typeof ClientCompanyCompanyNameAdminUserCreateRoute
  '/client/company/$companyName/batch/$batchId/edit': typeof ClientCompanyCompanyNameBatchBatchIdEditRoute
  '/client/company/$companyName/commodity/$commodityId/edit': typeof ClientCompanyCompanyNameCommodityCommodityIdEditRoute
  '/client/company/$companyName/geo-tag/$landId/edit': typeof ClientCompanyCompanyNameGeoTagLandIdEditRoute
  '/client/company/$companyName/worker/group/create': typeof ClientCompanyCompanyNameWorkerGroupCreateRoute
  '/client/company/$companyName/worker/individual/create': typeof ClientCompanyCompanyNameWorkerIndividualCreateRoute
  '/client/company/$companyName/admin/role': typeof ClientCompanyCompanyNameAdminRoleIndexRoute
  '/client/company/$companyName/admin/user': typeof ClientCompanyCompanyNameAdminUserIndexRoute
  '/client/company/$companyName/batch/$batchId': typeof ClientCompanyCompanyNameBatchBatchIdIndexRoute
  '/client/company/$companyName/commodity/$commodityId': typeof ClientCompanyCompanyNameCommodityCommodityIdIndexRoute
  '/client/company/$companyName/geo-tag/$landId': typeof ClientCompanyCompanyNameGeoTagLandIdIndexRoute
  '/client/company/$companyName/worker/group': typeof ClientCompanyCompanyNameWorkerGroupIndexRoute
  '/client/company/$companyName/worker/individual': typeof ClientCompanyCompanyNameWorkerIndividualIndexRoute
  '/client/company/$companyName/admin/role/$roleId/edit': typeof ClientCompanyCompanyNameAdminRoleRoleIdEditRoute
  '/client/company/$companyName/admin/user/$userId/edit': typeof ClientCompanyCompanyNameAdminUserUserIdEditRoute
  '/client/company/$companyName/batch/$batchId/attribute/create': typeof ClientCompanyCompanyNameBatchBatchIdAttributeCreateRoute
  '/client/company/$companyName/batch/$batchId/source/create': typeof ClientCompanyCompanyNameBatchBatchIdSourceCreateRoute
  '/client/company/$companyName/worker/group/$farmerGroupId/edit': typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRoute
  '/client/company/$companyName/worker/individual/$farmerId/edit': typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRoute
  '/client/company/$companyName/admin/role/$roleId': typeof ClientCompanyCompanyNameAdminRoleRoleIdIndexRoute
  '/client/company/$companyName/admin/user/$userId': typeof ClientCompanyCompanyNameAdminUserUserIdIndexRoute
  '/client/company/$companyName/worker/group/$farmerGroupId': typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRoute
  '/client/company/$companyName/worker/individual/$farmerId': typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRoute
  '/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit': typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRoute
  '/client/company/$companyName/batch/$batchId/source/$sourceId/edit': typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRoute
  '/client/company/$companyName/batch/$batchId/attribute/$attributeId': typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRoute
  '/client/company/$companyName/batch/$batchId/source/$sourceId': typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/client/companies/create': typeof ClientCompaniesCreateRoute
  '/client/company/$companyName': typeof ClientCompanyCompanyNameRouteWithChildren
  '/client/profile/edit': typeof ClientProfileEditRoute
  '/client/companies': typeof ClientCompaniesIndexRoute
  '/client/profile': typeof ClientProfileIndexRoute
  '/client/company/$companyName/billing': typeof ClientCompanyCompanyNameBillingRoute
  '/client/company/$companyName/setting': typeof ClientCompanyCompanyNameSettingRoute
  '/client/company/$companyName/admin/permission': typeof ClientCompanyCompanyNameAdminPermissionRoute
  '/client/company/$companyName/batch/create': typeof ClientCompanyCompanyNameBatchCreateRoute
  '/client/company/$companyName/commodity/create': typeof ClientCompanyCompanyNameCommodityCreateRoute
  '/client/company/$companyName/geo-tag/create': typeof ClientCompanyCompanyNameGeoTagCreateRoute
  '/client/company/$companyName/batch': typeof ClientCompanyCompanyNameBatchIndexRoute
  '/client/company/$companyName/commodity': typeof ClientCompanyCompanyNameCommodityIndexRoute
  '/client/company/$companyName/geo-tag': typeof ClientCompanyCompanyNameGeoTagIndexRoute
  '/client/company/$companyName/admin/role/create': typeof ClientCompanyCompanyNameAdminRoleCreateRoute
  '/client/company/$companyName/admin/user/create': typeof ClientCompanyCompanyNameAdminUserCreateRoute
  '/client/company/$companyName/batch/$batchId/edit': typeof ClientCompanyCompanyNameBatchBatchIdEditRoute
  '/client/company/$companyName/commodity/$commodityId/edit': typeof ClientCompanyCompanyNameCommodityCommodityIdEditRoute
  '/client/company/$companyName/geo-tag/$landId/edit': typeof ClientCompanyCompanyNameGeoTagLandIdEditRoute
  '/client/company/$companyName/worker/group/create': typeof ClientCompanyCompanyNameWorkerGroupCreateRoute
  '/client/company/$companyName/worker/individual/create': typeof ClientCompanyCompanyNameWorkerIndividualCreateRoute
  '/client/company/$companyName/admin/role': typeof ClientCompanyCompanyNameAdminRoleIndexRoute
  '/client/company/$companyName/admin/user': typeof ClientCompanyCompanyNameAdminUserIndexRoute
  '/client/company/$companyName/batch/$batchId': typeof ClientCompanyCompanyNameBatchBatchIdIndexRoute
  '/client/company/$companyName/commodity/$commodityId': typeof ClientCompanyCompanyNameCommodityCommodityIdIndexRoute
  '/client/company/$companyName/geo-tag/$landId': typeof ClientCompanyCompanyNameGeoTagLandIdIndexRoute
  '/client/company/$companyName/worker/group': typeof ClientCompanyCompanyNameWorkerGroupIndexRoute
  '/client/company/$companyName/worker/individual': typeof ClientCompanyCompanyNameWorkerIndividualIndexRoute
  '/client/company/$companyName/admin/role/$roleId/edit': typeof ClientCompanyCompanyNameAdminRoleRoleIdEditRoute
  '/client/company/$companyName/admin/user/$userId/edit': typeof ClientCompanyCompanyNameAdminUserUserIdEditRoute
  '/client/company/$companyName/batch/$batchId/attribute/create': typeof ClientCompanyCompanyNameBatchBatchIdAttributeCreateRoute
  '/client/company/$companyName/batch/$batchId/source/create': typeof ClientCompanyCompanyNameBatchBatchIdSourceCreateRoute
  '/client/company/$companyName/worker/group/$farmerGroupId/edit': typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRoute
  '/client/company/$companyName/worker/individual/$farmerId/edit': typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRoute
  '/client/company/$companyName/admin/role/$roleId': typeof ClientCompanyCompanyNameAdminRoleRoleIdIndexRoute
  '/client/company/$companyName/admin/user/$userId': typeof ClientCompanyCompanyNameAdminUserUserIdIndexRoute
  '/client/company/$companyName/worker/group/$farmerGroupId': typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRoute
  '/client/company/$companyName/worker/individual/$farmerId': typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRoute
  '/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit': typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRoute
  '/client/company/$companyName/batch/$batchId/source/$sourceId/edit': typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRoute
  '/client/company/$companyName/batch/$batchId/attribute/$attributeId': typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRoute
  '/client/company/$companyName/batch/$batchId/source/$sourceId': typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/client/companies/create': typeof ClientCompaniesCreateRoute
  '/client/company/$companyName': typeof ClientCompanyCompanyNameRouteWithChildren
  '/client/profile/edit': typeof ClientProfileEditRoute
  '/client/companies/': typeof ClientCompaniesIndexRoute
  '/client/profile/': typeof ClientProfileIndexRoute
  '/client/company/$companyName/billing': typeof ClientCompanyCompanyNameBillingRoute
  '/client/company/$companyName/setting': typeof ClientCompanyCompanyNameSettingRoute
  '/client/company/$companyName/admin/permission': typeof ClientCompanyCompanyNameAdminPermissionRoute
  '/client/company/$companyName/batch/create': typeof ClientCompanyCompanyNameBatchCreateRoute
  '/client/company/$companyName/commodity/create': typeof ClientCompanyCompanyNameCommodityCreateRoute
  '/client/company/$companyName/geo-tag/create': typeof ClientCompanyCompanyNameGeoTagCreateRoute
  '/client/company/$companyName/batch/': typeof ClientCompanyCompanyNameBatchIndexRoute
  '/client/company/$companyName/commodity/': typeof ClientCompanyCompanyNameCommodityIndexRoute
  '/client/company/$companyName/geo-tag/': typeof ClientCompanyCompanyNameGeoTagIndexRoute
  '/client/company/$companyName/admin/role/create': typeof ClientCompanyCompanyNameAdminRoleCreateRoute
  '/client/company/$companyName/admin/user/create': typeof ClientCompanyCompanyNameAdminUserCreateRoute
  '/client/company/$companyName/batch/$batchId/edit': typeof ClientCompanyCompanyNameBatchBatchIdEditRoute
  '/client/company/$companyName/commodity/$commodityId/edit': typeof ClientCompanyCompanyNameCommodityCommodityIdEditRoute
  '/client/company/$companyName/geo-tag/$landId/edit': typeof ClientCompanyCompanyNameGeoTagLandIdEditRoute
  '/client/company/$companyName/worker/group/create': typeof ClientCompanyCompanyNameWorkerGroupCreateRoute
  '/client/company/$companyName/worker/individual/create': typeof ClientCompanyCompanyNameWorkerIndividualCreateRoute
  '/client/company/$companyName/admin/role/': typeof ClientCompanyCompanyNameAdminRoleIndexRoute
  '/client/company/$companyName/admin/user/': typeof ClientCompanyCompanyNameAdminUserIndexRoute
  '/client/company/$companyName/batch/$batchId/': typeof ClientCompanyCompanyNameBatchBatchIdIndexRoute
  '/client/company/$companyName/commodity/$commodityId/': typeof ClientCompanyCompanyNameCommodityCommodityIdIndexRoute
  '/client/company/$companyName/geo-tag/$landId/': typeof ClientCompanyCompanyNameGeoTagLandIdIndexRoute
  '/client/company/$companyName/worker/group/': typeof ClientCompanyCompanyNameWorkerGroupIndexRoute
  '/client/company/$companyName/worker/individual/': typeof ClientCompanyCompanyNameWorkerIndividualIndexRoute
  '/client/company/$companyName/admin/role/$roleId/edit': typeof ClientCompanyCompanyNameAdminRoleRoleIdEditRoute
  '/client/company/$companyName/admin/user/$userId/edit': typeof ClientCompanyCompanyNameAdminUserUserIdEditRoute
  '/client/company/$companyName/batch/$batchId/attribute/create': typeof ClientCompanyCompanyNameBatchBatchIdAttributeCreateRoute
  '/client/company/$companyName/batch/$batchId/source/create': typeof ClientCompanyCompanyNameBatchBatchIdSourceCreateRoute
  '/client/company/$companyName/worker/group/$farmerGroupId/edit': typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRoute
  '/client/company/$companyName/worker/individual/$farmerId/edit': typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRoute
  '/client/company/$companyName/admin/role/$roleId/': typeof ClientCompanyCompanyNameAdminRoleRoleIdIndexRoute
  '/client/company/$companyName/admin/user/$userId/': typeof ClientCompanyCompanyNameAdminUserUserIdIndexRoute
  '/client/company/$companyName/worker/group/$farmerGroupId/': typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRoute
  '/client/company/$companyName/worker/individual/$farmerId/': typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRoute
  '/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit': typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRoute
  '/client/company/$companyName/batch/$batchId/source/$sourceId/edit': typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRoute
  '/client/company/$companyName/batch/$batchId/attribute/$attributeId/': typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRoute
  '/client/company/$companyName/batch/$batchId/source/$sourceId/': typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/email-verified'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/client/companies/create'
    | '/client/company/$companyName'
    | '/client/profile/edit'
    | '/client/companies'
    | '/client/profile'
    | '/client/company/$companyName/billing'
    | '/client/company/$companyName/setting'
    | '/client/company/$companyName/admin/permission'
    | '/client/company/$companyName/batch/create'
    | '/client/company/$companyName/commodity/create'
    | '/client/company/$companyName/geo-tag/create'
    | '/client/company/$companyName/batch'
    | '/client/company/$companyName/commodity'
    | '/client/company/$companyName/geo-tag'
    | '/client/company/$companyName/admin/role/create'
    | '/client/company/$companyName/admin/user/create'
    | '/client/company/$companyName/batch/$batchId/edit'
    | '/client/company/$companyName/commodity/$commodityId/edit'
    | '/client/company/$companyName/geo-tag/$landId/edit'
    | '/client/company/$companyName/worker/group/create'
    | '/client/company/$companyName/worker/individual/create'
    | '/client/company/$companyName/admin/role'
    | '/client/company/$companyName/admin/user'
    | '/client/company/$companyName/batch/$batchId'
    | '/client/company/$companyName/commodity/$commodityId'
    | '/client/company/$companyName/geo-tag/$landId'
    | '/client/company/$companyName/worker/group'
    | '/client/company/$companyName/worker/individual'
    | '/client/company/$companyName/admin/role/$roleId/edit'
    | '/client/company/$companyName/admin/user/$userId/edit'
    | '/client/company/$companyName/batch/$batchId/attribute/create'
    | '/client/company/$companyName/batch/$batchId/source/create'
    | '/client/company/$companyName/worker/group/$farmerGroupId/edit'
    | '/client/company/$companyName/worker/individual/$farmerId/edit'
    | '/client/company/$companyName/admin/role/$roleId'
    | '/client/company/$companyName/admin/user/$userId'
    | '/client/company/$companyName/worker/group/$farmerGroupId'
    | '/client/company/$companyName/worker/individual/$farmerId'
    | '/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit'
    | '/client/company/$companyName/batch/$batchId/source/$sourceId/edit'
    | '/client/company/$companyName/batch/$batchId/attribute/$attributeId'
    | '/client/company/$companyName/batch/$batchId/source/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/email-verified'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/client/companies/create'
    | '/client/company/$companyName'
    | '/client/profile/edit'
    | '/client/companies'
    | '/client/profile'
    | '/client/company/$companyName/billing'
    | '/client/company/$companyName/setting'
    | '/client/company/$companyName/admin/permission'
    | '/client/company/$companyName/batch/create'
    | '/client/company/$companyName/commodity/create'
    | '/client/company/$companyName/geo-tag/create'
    | '/client/company/$companyName/batch'
    | '/client/company/$companyName/commodity'
    | '/client/company/$companyName/geo-tag'
    | '/client/company/$companyName/admin/role/create'
    | '/client/company/$companyName/admin/user/create'
    | '/client/company/$companyName/batch/$batchId/edit'
    | '/client/company/$companyName/commodity/$commodityId/edit'
    | '/client/company/$companyName/geo-tag/$landId/edit'
    | '/client/company/$companyName/worker/group/create'
    | '/client/company/$companyName/worker/individual/create'
    | '/client/company/$companyName/admin/role'
    | '/client/company/$companyName/admin/user'
    | '/client/company/$companyName/batch/$batchId'
    | '/client/company/$companyName/commodity/$commodityId'
    | '/client/company/$companyName/geo-tag/$landId'
    | '/client/company/$companyName/worker/group'
    | '/client/company/$companyName/worker/individual'
    | '/client/company/$companyName/admin/role/$roleId/edit'
    | '/client/company/$companyName/admin/user/$userId/edit'
    | '/client/company/$companyName/batch/$batchId/attribute/create'
    | '/client/company/$companyName/batch/$batchId/source/create'
    | '/client/company/$companyName/worker/group/$farmerGroupId/edit'
    | '/client/company/$companyName/worker/individual/$farmerId/edit'
    | '/client/company/$companyName/admin/role/$roleId'
    | '/client/company/$companyName/admin/user/$userId'
    | '/client/company/$companyName/worker/group/$farmerGroupId'
    | '/client/company/$companyName/worker/individual/$farmerId'
    | '/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit'
    | '/client/company/$companyName/batch/$batchId/source/$sourceId/edit'
    | '/client/company/$companyName/batch/$batchId/attribute/$attributeId'
    | '/client/company/$companyName/batch/$batchId/source/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/email-verified'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/client/companies/create'
    | '/client/company/$companyName'
    | '/client/profile/edit'
    | '/client/companies/'
    | '/client/profile/'
    | '/client/company/$companyName/billing'
    | '/client/company/$companyName/setting'
    | '/client/company/$companyName/admin/permission'
    | '/client/company/$companyName/batch/create'
    | '/client/company/$companyName/commodity/create'
    | '/client/company/$companyName/geo-tag/create'
    | '/client/company/$companyName/batch/'
    | '/client/company/$companyName/commodity/'
    | '/client/company/$companyName/geo-tag/'
    | '/client/company/$companyName/admin/role/create'
    | '/client/company/$companyName/admin/user/create'
    | '/client/company/$companyName/batch/$batchId/edit'
    | '/client/company/$companyName/commodity/$commodityId/edit'
    | '/client/company/$companyName/geo-tag/$landId/edit'
    | '/client/company/$companyName/worker/group/create'
    | '/client/company/$companyName/worker/individual/create'
    | '/client/company/$companyName/admin/role/'
    | '/client/company/$companyName/admin/user/'
    | '/client/company/$companyName/batch/$batchId/'
    | '/client/company/$companyName/commodity/$commodityId/'
    | '/client/company/$companyName/geo-tag/$landId/'
    | '/client/company/$companyName/worker/group/'
    | '/client/company/$companyName/worker/individual/'
    | '/client/company/$companyName/admin/role/$roleId/edit'
    | '/client/company/$companyName/admin/user/$userId/edit'
    | '/client/company/$companyName/batch/$batchId/attribute/create'
    | '/client/company/$companyName/batch/$batchId/source/create'
    | '/client/company/$companyName/worker/group/$farmerGroupId/edit'
    | '/client/company/$companyName/worker/individual/$farmerId/edit'
    | '/client/company/$companyName/admin/role/$roleId/'
    | '/client/company/$companyName/admin/user/$userId/'
    | '/client/company/$companyName/worker/group/$farmerGroupId/'
    | '/client/company/$companyName/worker/individual/$farmerId/'
    | '/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit'
    | '/client/company/$companyName/batch/$batchId/source/$sourceId/edit'
    | '/client/company/$companyName/batch/$batchId/attribute/$attributeId/'
    | '/client/company/$companyName/batch/$batchId/source/$sourceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profile/': {
      id: '/client/profile/'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/companies/': {
      id: '/client/companies/'
      path: '/companies'
      fullPath: '/client/companies'
      preLoaderRoute: typeof ClientCompaniesIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile/edit': {
      id: '/client/profile/edit'
      path: '/profile/edit'
      fullPath: '/client/profile/edit'
      preLoaderRoute: typeof ClientProfileEditRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/company/$companyName': {
      id: '/client/company/$companyName'
      path: '/company/$companyName'
      fullPath: '/client/company/$companyName'
      preLoaderRoute: typeof ClientCompanyCompanyNameRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/companies/create': {
      id: '/client/companies/create'
      path: '/companies/create'
      fullPath: '/client/companies/create'
      preLoaderRoute: typeof ClientCompaniesCreateRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/company/$companyName/setting': {
      id: '/client/company/$companyName/setting'
      path: '/setting'
      fullPath: '/client/company/$companyName/setting'
      preLoaderRoute: typeof ClientCompanyCompanyNameSettingRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/billing': {
      id: '/client/company/$companyName/billing'
      path: '/billing'
      fullPath: '/client/company/$companyName/billing'
      preLoaderRoute: typeof ClientCompanyCompanyNameBillingRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/geo-tag/': {
      id: '/client/company/$companyName/geo-tag/'
      path: '/geo-tag'
      fullPath: '/client/company/$companyName/geo-tag'
      preLoaderRoute: typeof ClientCompanyCompanyNameGeoTagIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/commodity/': {
      id: '/client/company/$companyName/commodity/'
      path: '/commodity'
      fullPath: '/client/company/$companyName/commodity'
      preLoaderRoute: typeof ClientCompanyCompanyNameCommodityIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/': {
      id: '/client/company/$companyName/batch/'
      path: '/batch'
      fullPath: '/client/company/$companyName/batch'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/geo-tag/create': {
      id: '/client/company/$companyName/geo-tag/create'
      path: '/geo-tag/create'
      fullPath: '/client/company/$companyName/geo-tag/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameGeoTagCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/commodity/create': {
      id: '/client/company/$companyName/commodity/create'
      path: '/commodity/create'
      fullPath: '/client/company/$companyName/commodity/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameCommodityCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/create': {
      id: '/client/company/$companyName/batch/create'
      path: '/batch/create'
      fullPath: '/client/company/$companyName/batch/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/admin/permission': {
      id: '/client/company/$companyName/admin/permission'
      path: '/admin/permission'
      fullPath: '/client/company/$companyName/admin/permission'
      preLoaderRoute: typeof ClientCompanyCompanyNameAdminPermissionRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/worker/individual/': {
      id: '/client/company/$companyName/worker/individual/'
      path: '/worker/individual'
      fullPath: '/client/company/$companyName/worker/individual'
      preLoaderRoute: typeof ClientCompanyCompanyNameWorkerIndividualIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/worker/group/': {
      id: '/client/company/$companyName/worker/group/'
      path: '/worker/group'
      fullPath: '/client/company/$companyName/worker/group'
      preLoaderRoute: typeof ClientCompanyCompanyNameWorkerGroupIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/geo-tag/$landId/': {
      id: '/client/company/$companyName/geo-tag/$landId/'
      path: '/geo-tag/$landId'
      fullPath: '/client/company/$companyName/geo-tag/$landId'
      preLoaderRoute: typeof ClientCompanyCompanyNameGeoTagLandIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/commodity/$commodityId/': {
      id: '/client/company/$companyName/commodity/$commodityId/'
      path: '/commodity/$commodityId'
      fullPath: '/client/company/$companyName/commodity/$commodityId'
      preLoaderRoute: typeof ClientCompanyCompanyNameCommodityCommodityIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/$batchId/': {
      id: '/client/company/$companyName/batch/$batchId/'
      path: '/batch/$batchId'
      fullPath: '/client/company/$companyName/batch/$batchId'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchBatchIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/admin/user/': {
      id: '/client/company/$companyName/admin/user/'
      path: '/admin/user'
      fullPath: '/client/company/$companyName/admin/user'
      preLoaderRoute: typeof ClientCompanyCompanyNameAdminUserIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/admin/role/': {
      id: '/client/company/$companyName/admin/role/'
      path: '/admin/role'
      fullPath: '/client/company/$companyName/admin/role'
      preLoaderRoute: typeof ClientCompanyCompanyNameAdminRoleIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/worker/individual/create': {
      id: '/client/company/$companyName/worker/individual/create'
      path: '/worker/individual/create'
      fullPath: '/client/company/$companyName/worker/individual/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameWorkerIndividualCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/worker/group/create': {
      id: '/client/company/$companyName/worker/group/create'
      path: '/worker/group/create'
      fullPath: '/client/company/$companyName/worker/group/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameWorkerGroupCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/geo-tag/$landId/edit': {
      id: '/client/company/$companyName/geo-tag/$landId/edit'
      path: '/geo-tag/$landId/edit'
      fullPath: '/client/company/$companyName/geo-tag/$landId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameGeoTagLandIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/commodity/$commodityId/edit': {
      id: '/client/company/$companyName/commodity/$commodityId/edit'
      path: '/commodity/$commodityId/edit'
      fullPath: '/client/company/$companyName/commodity/$commodityId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameCommodityCommodityIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/$batchId/edit': {
      id: '/client/company/$companyName/batch/$batchId/edit'
      path: '/batch/$batchId/edit'
      fullPath: '/client/company/$companyName/batch/$batchId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchBatchIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/admin/user/create': {
      id: '/client/company/$companyName/admin/user/create'
      path: '/admin/user/create'
      fullPath: '/client/company/$companyName/admin/user/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameAdminUserCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/admin/role/create': {
      id: '/client/company/$companyName/admin/role/create'
      path: '/admin/role/create'
      fullPath: '/client/company/$companyName/admin/role/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameAdminRoleCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/worker/individual/$farmerId/': {
      id: '/client/company/$companyName/worker/individual/$farmerId/'
      path: '/worker/individual/$farmerId'
      fullPath: '/client/company/$companyName/worker/individual/$farmerId'
      preLoaderRoute: typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/worker/group/$farmerGroupId/': {
      id: '/client/company/$companyName/worker/group/$farmerGroupId/'
      path: '/worker/group/$farmerGroupId'
      fullPath: '/client/company/$companyName/worker/group/$farmerGroupId'
      preLoaderRoute: typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/admin/user/$userId/': {
      id: '/client/company/$companyName/admin/user/$userId/'
      path: '/admin/user/$userId'
      fullPath: '/client/company/$companyName/admin/user/$userId'
      preLoaderRoute: typeof ClientCompanyCompanyNameAdminUserUserIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/admin/role/$roleId/': {
      id: '/client/company/$companyName/admin/role/$roleId/'
      path: '/admin/role/$roleId'
      fullPath: '/client/company/$companyName/admin/role/$roleId'
      preLoaderRoute: typeof ClientCompanyCompanyNameAdminRoleRoleIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/worker/individual/$farmerId/edit': {
      id: '/client/company/$companyName/worker/individual/$farmerId/edit'
      path: '/worker/individual/$farmerId/edit'
      fullPath: '/client/company/$companyName/worker/individual/$farmerId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/worker/group/$farmerGroupId/edit': {
      id: '/client/company/$companyName/worker/group/$farmerGroupId/edit'
      path: '/worker/group/$farmerGroupId/edit'
      fullPath: '/client/company/$companyName/worker/group/$farmerGroupId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/$batchId/source/create': {
      id: '/client/company/$companyName/batch/$batchId/source/create'
      path: '/batch/$batchId/source/create'
      fullPath: '/client/company/$companyName/batch/$batchId/source/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchBatchIdSourceCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/$batchId/attribute/create': {
      id: '/client/company/$companyName/batch/$batchId/attribute/create'
      path: '/batch/$batchId/attribute/create'
      fullPath: '/client/company/$companyName/batch/$batchId/attribute/create'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchBatchIdAttributeCreateRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/admin/user/$userId/edit': {
      id: '/client/company/$companyName/admin/user/$userId/edit'
      path: '/admin/user/$userId/edit'
      fullPath: '/client/company/$companyName/admin/user/$userId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameAdminUserUserIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/admin/role/$roleId/edit': {
      id: '/client/company/$companyName/admin/role/$roleId/edit'
      path: '/admin/role/$roleId/edit'
      fullPath: '/client/company/$companyName/admin/role/$roleId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameAdminRoleRoleIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/$batchId/source/$sourceId/': {
      id: '/client/company/$companyName/batch/$batchId/source/$sourceId/'
      path: '/batch/$batchId/source/$sourceId'
      fullPath: '/client/company/$companyName/batch/$batchId/source/$sourceId'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/$batchId/attribute/$attributeId/': {
      id: '/client/company/$companyName/batch/$batchId/attribute/$attributeId/'
      path: '/batch/$batchId/attribute/$attributeId'
      fullPath: '/client/company/$companyName/batch/$batchId/attribute/$attributeId'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/$batchId/source/$sourceId/edit': {
      id: '/client/company/$companyName/batch/$batchId/source/$sourceId/edit'
      path: '/batch/$batchId/source/$sourceId/edit'
      fullPath: '/client/company/$companyName/batch/$batchId/source/$sourceId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
    '/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit': {
      id: '/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit'
      path: '/batch/$batchId/attribute/$attributeId/edit'
      fullPath: '/client/company/$companyName/batch/$batchId/attribute/$attributeId/edit'
      preLoaderRoute: typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRouteImport
      parentRoute: typeof ClientCompanyCompanyNameRoute
    }
  }
}

interface ClientCompanyCompanyNameRouteChildren {
  ClientCompanyCompanyNameBillingRoute: typeof ClientCompanyCompanyNameBillingRoute
  ClientCompanyCompanyNameSettingRoute: typeof ClientCompanyCompanyNameSettingRoute
  ClientCompanyCompanyNameAdminPermissionRoute: typeof ClientCompanyCompanyNameAdminPermissionRoute
  ClientCompanyCompanyNameBatchCreateRoute: typeof ClientCompanyCompanyNameBatchCreateRoute
  ClientCompanyCompanyNameCommodityCreateRoute: typeof ClientCompanyCompanyNameCommodityCreateRoute
  ClientCompanyCompanyNameGeoTagCreateRoute: typeof ClientCompanyCompanyNameGeoTagCreateRoute
  ClientCompanyCompanyNameBatchIndexRoute: typeof ClientCompanyCompanyNameBatchIndexRoute
  ClientCompanyCompanyNameCommodityIndexRoute: typeof ClientCompanyCompanyNameCommodityIndexRoute
  ClientCompanyCompanyNameGeoTagIndexRoute: typeof ClientCompanyCompanyNameGeoTagIndexRoute
  ClientCompanyCompanyNameAdminRoleCreateRoute: typeof ClientCompanyCompanyNameAdminRoleCreateRoute
  ClientCompanyCompanyNameAdminUserCreateRoute: typeof ClientCompanyCompanyNameAdminUserCreateRoute
  ClientCompanyCompanyNameBatchBatchIdEditRoute: typeof ClientCompanyCompanyNameBatchBatchIdEditRoute
  ClientCompanyCompanyNameCommodityCommodityIdEditRoute: typeof ClientCompanyCompanyNameCommodityCommodityIdEditRoute
  ClientCompanyCompanyNameGeoTagLandIdEditRoute: typeof ClientCompanyCompanyNameGeoTagLandIdEditRoute
  ClientCompanyCompanyNameWorkerGroupCreateRoute: typeof ClientCompanyCompanyNameWorkerGroupCreateRoute
  ClientCompanyCompanyNameWorkerIndividualCreateRoute: typeof ClientCompanyCompanyNameWorkerIndividualCreateRoute
  ClientCompanyCompanyNameAdminRoleIndexRoute: typeof ClientCompanyCompanyNameAdminRoleIndexRoute
  ClientCompanyCompanyNameAdminUserIndexRoute: typeof ClientCompanyCompanyNameAdminUserIndexRoute
  ClientCompanyCompanyNameBatchBatchIdIndexRoute: typeof ClientCompanyCompanyNameBatchBatchIdIndexRoute
  ClientCompanyCompanyNameCommodityCommodityIdIndexRoute: typeof ClientCompanyCompanyNameCommodityCommodityIdIndexRoute
  ClientCompanyCompanyNameGeoTagLandIdIndexRoute: typeof ClientCompanyCompanyNameGeoTagLandIdIndexRoute
  ClientCompanyCompanyNameWorkerGroupIndexRoute: typeof ClientCompanyCompanyNameWorkerGroupIndexRoute
  ClientCompanyCompanyNameWorkerIndividualIndexRoute: typeof ClientCompanyCompanyNameWorkerIndividualIndexRoute
  ClientCompanyCompanyNameAdminRoleRoleIdEditRoute: typeof ClientCompanyCompanyNameAdminRoleRoleIdEditRoute
  ClientCompanyCompanyNameAdminUserUserIdEditRoute: typeof ClientCompanyCompanyNameAdminUserUserIdEditRoute
  ClientCompanyCompanyNameBatchBatchIdAttributeCreateRoute: typeof ClientCompanyCompanyNameBatchBatchIdAttributeCreateRoute
  ClientCompanyCompanyNameBatchBatchIdSourceCreateRoute: typeof ClientCompanyCompanyNameBatchBatchIdSourceCreateRoute
  ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRoute: typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRoute
  ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRoute: typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRoute
  ClientCompanyCompanyNameAdminRoleRoleIdIndexRoute: typeof ClientCompanyCompanyNameAdminRoleRoleIdIndexRoute
  ClientCompanyCompanyNameAdminUserUserIdIndexRoute: typeof ClientCompanyCompanyNameAdminUserUserIdIndexRoute
  ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRoute: typeof ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRoute
  ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRoute: typeof ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRoute
  ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRoute: typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRoute
  ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRoute: typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRoute
  ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRoute: typeof ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRoute
  ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRoute: typeof ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRoute
}

const ClientCompanyCompanyNameRouteChildren: ClientCompanyCompanyNameRouteChildren =
  {
    ClientCompanyCompanyNameBillingRoute: ClientCompanyCompanyNameBillingRoute,
    ClientCompanyCompanyNameSettingRoute: ClientCompanyCompanyNameSettingRoute,
    ClientCompanyCompanyNameAdminPermissionRoute:
      ClientCompanyCompanyNameAdminPermissionRoute,
    ClientCompanyCompanyNameBatchCreateRoute:
      ClientCompanyCompanyNameBatchCreateRoute,
    ClientCompanyCompanyNameCommodityCreateRoute:
      ClientCompanyCompanyNameCommodityCreateRoute,
    ClientCompanyCompanyNameGeoTagCreateRoute:
      ClientCompanyCompanyNameGeoTagCreateRoute,
    ClientCompanyCompanyNameBatchIndexRoute:
      ClientCompanyCompanyNameBatchIndexRoute,
    ClientCompanyCompanyNameCommodityIndexRoute:
      ClientCompanyCompanyNameCommodityIndexRoute,
    ClientCompanyCompanyNameGeoTagIndexRoute:
      ClientCompanyCompanyNameGeoTagIndexRoute,
    ClientCompanyCompanyNameAdminRoleCreateRoute:
      ClientCompanyCompanyNameAdminRoleCreateRoute,
    ClientCompanyCompanyNameAdminUserCreateRoute:
      ClientCompanyCompanyNameAdminUserCreateRoute,
    ClientCompanyCompanyNameBatchBatchIdEditRoute:
      ClientCompanyCompanyNameBatchBatchIdEditRoute,
    ClientCompanyCompanyNameCommodityCommodityIdEditRoute:
      ClientCompanyCompanyNameCommodityCommodityIdEditRoute,
    ClientCompanyCompanyNameGeoTagLandIdEditRoute:
      ClientCompanyCompanyNameGeoTagLandIdEditRoute,
    ClientCompanyCompanyNameWorkerGroupCreateRoute:
      ClientCompanyCompanyNameWorkerGroupCreateRoute,
    ClientCompanyCompanyNameWorkerIndividualCreateRoute:
      ClientCompanyCompanyNameWorkerIndividualCreateRoute,
    ClientCompanyCompanyNameAdminRoleIndexRoute:
      ClientCompanyCompanyNameAdminRoleIndexRoute,
    ClientCompanyCompanyNameAdminUserIndexRoute:
      ClientCompanyCompanyNameAdminUserIndexRoute,
    ClientCompanyCompanyNameBatchBatchIdIndexRoute:
      ClientCompanyCompanyNameBatchBatchIdIndexRoute,
    ClientCompanyCompanyNameCommodityCommodityIdIndexRoute:
      ClientCompanyCompanyNameCommodityCommodityIdIndexRoute,
    ClientCompanyCompanyNameGeoTagLandIdIndexRoute:
      ClientCompanyCompanyNameGeoTagLandIdIndexRoute,
    ClientCompanyCompanyNameWorkerGroupIndexRoute:
      ClientCompanyCompanyNameWorkerGroupIndexRoute,
    ClientCompanyCompanyNameWorkerIndividualIndexRoute:
      ClientCompanyCompanyNameWorkerIndividualIndexRoute,
    ClientCompanyCompanyNameAdminRoleRoleIdEditRoute:
      ClientCompanyCompanyNameAdminRoleRoleIdEditRoute,
    ClientCompanyCompanyNameAdminUserUserIdEditRoute:
      ClientCompanyCompanyNameAdminUserUserIdEditRoute,
    ClientCompanyCompanyNameBatchBatchIdAttributeCreateRoute:
      ClientCompanyCompanyNameBatchBatchIdAttributeCreateRoute,
    ClientCompanyCompanyNameBatchBatchIdSourceCreateRoute:
      ClientCompanyCompanyNameBatchBatchIdSourceCreateRoute,
    ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRoute:
      ClientCompanyCompanyNameWorkerGroupFarmerGroupIdEditRoute,
    ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRoute:
      ClientCompanyCompanyNameWorkerIndividualFarmerIdEditRoute,
    ClientCompanyCompanyNameAdminRoleRoleIdIndexRoute:
      ClientCompanyCompanyNameAdminRoleRoleIdIndexRoute,
    ClientCompanyCompanyNameAdminUserUserIdIndexRoute:
      ClientCompanyCompanyNameAdminUserUserIdIndexRoute,
    ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRoute:
      ClientCompanyCompanyNameWorkerGroupFarmerGroupIdIndexRoute,
    ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRoute:
      ClientCompanyCompanyNameWorkerIndividualFarmerIdIndexRoute,
    ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRoute:
      ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdEditRoute,
    ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRoute:
      ClientCompanyCompanyNameBatchBatchIdSourceSourceIdEditRoute,
    ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRoute:
      ClientCompanyCompanyNameBatchBatchIdAttributeAttributeIdIndexRoute,
    ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRoute:
      ClientCompanyCompanyNameBatchBatchIdSourceSourceIdIndexRoute,
  }

const ClientCompanyCompanyNameRouteWithChildren =
  ClientCompanyCompanyNameRoute._addFileChildren(
    ClientCompanyCompanyNameRouteChildren,
  )

interface ClientRouteChildren {
  ClientCompaniesCreateRoute: typeof ClientCompaniesCreateRoute
  ClientCompanyCompanyNameRoute: typeof ClientCompanyCompanyNameRouteWithChildren
  ClientProfileEditRoute: typeof ClientProfileEditRoute
  ClientCompaniesIndexRoute: typeof ClientCompaniesIndexRoute
  ClientProfileIndexRoute: typeof ClientProfileIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientCompaniesCreateRoute: ClientCompaniesCreateRoute,
  ClientCompanyCompanyNameRoute: ClientCompanyCompanyNameRouteWithChildren,
  ClientProfileEditRoute: ClientProfileEditRoute,
  ClientCompaniesIndexRoute: ClientCompaniesIndexRoute,
  ClientProfileIndexRoute: ClientProfileIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  EmailVerifiedRoute: EmailVerifiedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
